# // prompt_config = {
# //     "prompt_template": "Please provide a clear and step-by-step solution for a scientific problem in the categories of Chemistry, Physics, or Mathematics. The problem will specify the unit of measurement, which should not be included in the answer. Express the final answer as a decimal number with three digits after the decimal point. Conclude the answer by stating "The answer is therefore \boxed{[ANSWER]}.""
# // }
prompt_config = {
    "prompt_template_baseline_variant": "Please provide a clear and step-by-step solution for a scientific problem in the categories of Chemistry, Physics, or Mathematics. The problem will specify the unit of measurement, which should not be included in the answer. Express the final answer as a decimal number with three digits after the decimal point. Conclude the answer by stating \"The answer is therefore \\boxed{[ANSWER]}.\" You may start with your solution; do not repeat the prompt!",
    "cot_prompt_template": "Please provide a clear and step-by-step solution for a scientific problem in the categories of Chemistry, Physics, or Mathematics. The problem will specify the unit of measurement, which should not be included in the answer. Express the final answer as a decimal number with three digits after the decimal point. Conclude the answer by stating \"The answer is therefore \\boxed{[ANSWER]}.\"",
    # "pot_prompt_template": "Please provide a clear and step-by-step solution using python code generation to show your reasoning for a scientific problem in the categories of Chemistry, Physics, or Mathematics. The problem will specify the unit of measurement, which should not be included in the answer. Express the final answer as a decimal number with three digits after the decimal point. Conclude the answer by stating \"The answer is therefore \\boxed{[ANSWER]}.\"",
    "pot_prompt_template": "Please provide a clear and step-by-step solution for a scientific problem in the categories of Chemistry, Physics, or Mathematics. Use Python code to demonstrate your calculations where appropriate, showing the mathematical steps as executable code with explanatory comments. The problem will specify the unit of measurement, which should not be included in the answer. Express the final answer as a decimal number with three digits after the decimal point. Conclude the answer by stating \"The answer is therefore \\boxed{[ANSWER]}.\"",
}

